### ISSUE TITLE
Can't run on Pixel 2 XL

### ISSUE THREAD

**Issue by JohanLindell** [joaquim-verges/DeeplabAndroid#1]
Wanted to play around with the app but any attempts of running it on my Pixel 2 XL fails with the following error message. Tried to find documentation on the model or a similar issue that has been resolved but so far I haven't found anything. Any idea on how to debug?

```
E/DeeplabAndroid: Analyzer Error
    java.lang.IllegalArgumentException: Internal error: Failed to run on the given Interpreter: OpenCL library not loaded - dlopen failed: library "libOpenCL-pixel.so" not found
    Falling back to OpenGL
    TfLiteGpuDelegate Invoke: Write to buffer failed. Source data is larger than buffer.
    Node number 70 (TfLiteGpuDelegateV2) failed to invoke.
    
    TfLiteGpuDelegate Invoke: Write to buffer failed. Source data is larger than buffer.
    Node number 70 (TfLiteGpuDelegateV2) failed to invoke.
    
    TfLiteGpuDelegate Invoke: Write to buffer failed. Source data is lar
        at org.tensorflow.lite.NativeInterpreterWrapper.run(Native Method)
        at org.tensorflow.lite.NativeInterpreterWrapper.run(NativeInterpreterWrapper.java:152)
        at org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs(Interpreter.java:296)
        at org.tensorflow.lite.Interpreter.run(Interpreter.java:259)
        at com.joaquimverges.deeplabandroid.ImageSegmentationAnalyzer.analyze(ImageSegmentationAnalyzer.kt:174)
        at androidx.camera.core.ImageAnalysisAbstractAnalyzer.analyzeImage(ImageAnalysisAbstractAnalyzer.java:56)
        at androidx.camera.core.ImageAnalysisNonBlockingAnalyzer$1.run(ImageAnalysisNonBlockingAnalyzer.java:138)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
```

**Comment by joaquim-verges** [comment]
Thanks for the report Johan!

my intuition is that the Pixel 2 doesn't support GPU acceleration, which I added to the tflite options at this line: https://github.com/joaquim-verges/DeeplabAndroid/blob/c7020a9ecb8a7f15592c3bd3c81174fe00577ba9/app/src/main/java/com/joaquimverges/deeplabandroid/ImageSegmentationAnalyzer.kt#L61

Can you try removing `.addDelegate(GpuDelegate())` from that line and see if it works for you?

I'll look for a way to check for the device's GPU compatibility before adding that option.

**Comment by JohanLindell** [comment]
Yeah that did it. Though I'm surprised that the Pixel 2 XL doesn't support it, it feels like it came out after much of the initial deep learning API stuff were originally launched. Thanks!
